import pygame
pygame.init()

Goldie          = pygame.font.Font("assets/Fonts/Goldie.ttf",60)
Demon_Blade     = pygame.font.Font("assets/Fonts/Demon_Blade.otf",90)
Demon_Blade_big = pygame.font.Font("assets/Fonts/Demon_Blade.otf",120)
NixieOne_small  = pygame.font.Font("assets/Fonts/NixieOne.otf",25)
NixieOne        = pygame.font.Font("assets/Fonts/NixieOne.otf",32)
Sofia_small     = pygame.font.Font("assets/Fonts/Sofia.otf",25)
Sofia           = pygame.font.Font("assets/Fonts/Sofia.otf",50)
Quicksand_small = pygame.font.Font("assets/Fonts/Quicksand.otf",25)
Quicksand       = pygame.font.Font("assets/Fonts/Quicksand.otf",50)
Chomsky         = pygame.font.Font("assets/Fonts/Chomsky.otf",32)
A1942report     = pygame.font.Font("assets/Fonts/A1942report.ttf",50)
DirtyFox        = pygame.font.Font("assets/Fonts/DirtyFox.ttf",50)
